### ISSUE TITLE
Add Domain or User and get an error

### ISSUE THREAD

**Issue by patrickmemmer** [coax/hmailserver-webadmin#15]
Hi,
i've installed your webadmin als you wrote. 
i have a Server 2016 with mssql 2016 and iis

Can access to the really nice webadmin but if i create a new domain or so i've got this error:
Operation failed
 Description: Source: hMailServer COM library
Description: Failed to save object. Another domain with this name already exists.
 Script: background_domain_save.php
When i go back - the Domain is created
When i create a User i've got this error:
Operation failed
 Description: Source: hMailServer COM library
Description: Failed to save object. Another domain with this name already exists.
 Script: background_domain_name_save.php
When i create a rule and press create - it creates two rules.

**Comment by coax** [comment]
I cannot reproduce this error. It might have to do with incorrect setup.
