### ISSUE TITLE
Log Parser not loading log

### ISSUE THREAD

**Issue by mdowling76** [coax/hmailserver-webadmin#17]
Getting an error on the log parser. The old log parser does work. How can I troubleshoot this?

**Comment by coax** [comment]
I'll take a look

**Comment by mdowling76** [comment]
Hi, just a bit more info: I have the logs on a separate disk F:\Data\hMailServer\Logs and am running the latest version of hMailServer and WebAdmin. 
I suspect an issue in either the path not being read from hMailServer (ini?) Don't really understand how you are doing this now. (I'm not into php scripting.)

**Comment by AlexandreGagner** [comment]
Hi,
I add more info too, I'm running hMmail with different path for log too, I tested with smtp log and it was crashing with php Allowed Memory Size error (very big logs files to parse), It's was working with low lines logs files like error.
I just configured my memory_limit in php server configuration and now it's working (it's take about 10s to load with 11Mo ajax request)
Have a nice day
