### ISSUE TITLE
Prevent passing APIPA addresses to public geo ip service

### ISSUE THREAD

**Issue by estradis** [coax/hmailserver-webadmin#18]
In "hm_securityrange.php" in function geoIp (line 102-113 in v1.4) you filter out all private addresses to prevent asking public services for these addresses. 
`
$regex = '/(127\.0\.0\.1)|^(10\.)|^(192\.168\.)|^(172\.(1[6-9]|2[0-9]|3[0-1]))/';
`
`
if (preg_match($regex, $ip)) return Translate('Local IP range');
`
**But you forgot the apipa range!** 
These are also private addresses, automatically set by os when the network adapter needs to obtain a dynamic address, but no dhcp server responded. Therefore your regex should be:
`
$regex = '/(127\.0\.0\.1)|^(10\.)|^(192\.168\.)|^(169\.254\.)|^(172\.(1[6-9]|2[0-9]|3[0-1]))/';
`

See also:
https://en.wikipedia.org/wiki/Link-local_address
https://en.wikipedia.org/wiki/Zero-configuration_networking

**Comment by coax** [comment]
Thanks, it will be implemented into v1.5
