### ISSUE TITLE
Invalid CSRF token when deleting rule in hm_account.php

### ISSUE THREAD

**Issue by RvdHout** [coax/hmailserver-webadmin#19]
hm_account.php line 275

`                  <td><a href="#" onclick="return Confirm(\'' . $str_confirm . ' <b>' . $rulename . '</b>:\',\'' . $str_yes . '\',\'' . $str_no . '\',\'?page=background_rule_save&action=delete&savetype=rule&domainid=' . $DomainId . '&accountid=' . $AccountId . '&ruleid=' . $ruleid . '\');" class="delete" title="' . $str_delete . '&csrftoken=' . $csrftoken . '">' . $str_delete . '</a></td>`

should be 
`                  <td><a href="#" onclick="return Confirm(\'' . $str_confirm . ' <b>' . $rulename . '</b>:\',\'' . $str_yes . '\',\'' . $str_no . '\',\'?page=background_rule_save&action=delete&savetype=rule&domainid=' . $DomainId . '&accountid=' . $AccountId . '&ruleid=' . $ruleid . '&csrftoken=' . $csrftoken . '\');" class="delete" title="' . $str_delete . '">' . $str_delete . '</a></td>`

**Comment by coax** [comment]
Thanks, fixed.
