### ISSUE TITLE
Can you put download link for PHPWebAdmin?

### ISSUE THREAD

**Issue by amanjuman** [coax/hmailserver-webadmin#20]
I'm searching PHPWebAdmin all around but not getting, without this installation is not possible, so please provide link.

**Comment by coax** [comment]
PHPWebAdmin is included in hMailServer installation here: https://www.hmailserver.com/download
Or download from HMS GitHub: https://github.com/hmailserver/hmailserver/tree/master/hmailserver/source/WebAdmin

If you need hMailAdmin, it's here: https://github.com/coax/hmailserver-webadmin/releases/latest

**Comment by amanjuman** [comment]
Extract "hMailAdmin" folder in the same root as "PHPWebAdmin" folder
But where do I get that PHPWebAdmin? It didn't come with hmailserver.

**Comment by amanjuman** [comment]
Aw, I didn't saw that. Thanks

**Comment by coax** [comment]
Extracting to root means to extract to hMailServer folder (eg. C:/Program Files/hMailServer/)
