### ISSUE TITLE
Large domains exceed the sidebar limit

### ISSUE THREAD

**Issue by mvldebian** [coax/hmailserver-webadmin#21]
Very large domains exceed the sidebar limit
Onlye on domain admin or user page

![example](https://user-images.githubusercontent.com/25337130/53730319-58d56380-3e56-11e9-8fc4-51ae0827095a.JPG)

**Comment by coax** [comment]
Okay, do you have a suggestion?

**Comment by mstenz** [comment]
> 
> 
> Okay, do you have a suggestion?

maybe make left side bar wider, today anyhow everyone have such big wide screens and it seems even "normal sized" emailaddresses doesnt fit. 
For sure this only solve the issue half as there will be always email addressses that are wider than the space, and for this I don't have any answer.

**Comment by mvldebian** [comment]
I believe that resizing the bar will bring greater problems with the content of the page.

I think that instead of email a generic text like "My Account" would solve the problem without affecting the layout as a whole

![example](https://user-images.githubusercontent.com/25337130/53732367-7efe0200-3e5c-11e9-95a2-c2b7f1ca5162.JPG)

**Comment by coax** [comment]
What about three dots "..." at the end if text wider than column?

**Comment by mvldebian** [comment]
is also a good option. is that the email is already in the upper right corner when the user logs in.
"My Account" would be visually cleaner, I believe.

**Comment by coax** [comment]
Fix: https://github.com/coax/hmailserver-webadmin/blob/master/hMailAdmin/css/core.css

**Comment by mvldebian** [comment]
Nice job! Thanks  :)

![capturar](https://user-images.githubusercontent.com/25337130/53734903-17e44b80-3e64-11e9-97bd-55f9d646a5e7.JPG)
