### ISSUE TITLE
Not an Issue but a thank you.

### ISSUE THREAD

**Issue by visualperception** [coax/hmailserver-webadmin#24]
Nice work you've done here.
Do you think this will this ever get included in the production distribution of hMailServer?

**Comment by coax** [comment]
Author of hMailServer never commented this project on forums so there's no knowing whether or not it will be implemented into official release.

**Comment by visualperception** [comment]
Since hmailserver is now open source you should be able to setup a pull request to get it included if thats what you would like to do.

**Comment by visualperception** [comment]
Might be worthwhile asking Martin if he would like to include it first.
You can use https://www.hmailserver.com/contact
