### ISSUE TITLE
Undefined index: datepicker_weekStart

### ISSUE THREAD

**Issue by amir110** [coax/hmailserver-webadmin#25]
i have phpadmin installed and then override webadmin downloaded from repository.
the following error return and page remain white (not loaded).

<link rel="icon" href="favicon.ico">
  <script>var hmail_config = {weekStart:      <h2>Operation failed</h2>
      <p>Description: Undefined index: datepicker_weekStart</p>
      <p>Line: 72</p>
      <p>Script: index.php</p>

"End of response and remaining is not rendered to browser"

how i can solve this error?

**Comment by coax** [comment]
Have you tried downloading hMailAdmin again? It probably didn't download properly.
