### ISSUE TITLE
PHP7.4 and get_magic_quotes_gpc()

### ISSUE THREAD

**Issue by Andyt8** [coax/hmailserver-webadmin#28]
I found a problem between hmailserver-webadmin 1.5 and PHP 7.4. If I change to the latest version, hmailserver shows me the following error messages:

>>>Error in web browser
At the moment it Operation failed

Description: Function get_magic_quotes_gpc() is deprecated

Line: 26

Script: functions.php
<<<

It didn't worked to delete the associated lines from functions.php:
>>>from function.php
	if (get_magic_quotes_gpc())
		$retval = stripslashes($retval);
<<<

If I do that, then I see only a white page...

It look like hmailserver-webadmin is not able to operate with PHP7.4 - however, it still work with 7.3 for the moment.

**Comment by coax** [comment]
Already solved #27 , you need to download new file

**Comment by Andyt8** [comment]
Thank you for your fast answer. It's nice to hear the info, but I used the latest release and it still don't work. According to the release number, it show me the same at the code section.

Therefore it seems to me, the fix was only fixed in the code without changing version number. Maybe it would be a good idea to change the version number?

edit: resolved mistakes

**Comment by coax** [comment]
Just download the files that were recently changed (https://github.com/coax/hmailserver-webadmin/blob/master/hMailAdmin/include/functions.php), not the whole release because I haven't published a new version with all the minor fixes that were done.

**Comment by Andyt8** [comment]
Perfect. It worked for me. Thanks for your help.
