### ISSUE TITLE
Feature Request - Breadcrumbs

### ISSUE THREAD

**Issue by umairmalik2410** [coax/hmailserver-webadmin#29]
It would be really helpful if breadcrumbs can be added to the code. 

https://www.w3schools.com/howto/howto_css_breadcrumbs.asp

I'm sorry if this isn't the right place for feature requests. 

Thank you all for your hard work on this project :)

**Comment by umairmalik2410** [comment]
This is mainly for the domains/accounts section - this idea came into my mind when using the rules section of the domain >> accounts section.

**Comment by coax** [comment]
Added in v1.6
