### ISSUE TITLE
Can't access account page on mobile version

### ISSUE THREAD

**Issue by Lxxrxns** [coax/hmailserver-webadmin#30]
On desktop, when you click on your email address in the left menu, you can access an account page where you can set an auto reply and change other account settings, but on the responsive mobile version (phone and tablet) clicking your own email address opens and closes the sub menu with the "External accounts" item. It is impossible to access account settings this way, even when using "Desktop version" in Chrome for Android...

![Screenshot_2020-09-03-20-14-20-37~2](https://user-images.githubusercontent.com/12428228/92151970-3d1f9480-ee22-11ea-816a-ae5e33957899.jpg)

**Comment by coax** [comment]
Added "Account" link (above "External accounts") which is clickable on mobile.
