### ISSUE TITLE
Dmac reports

### ISSUE THREAD

**Issue by umairmalik2410** [coax/hmailserver-webadmin#42]
Nothing shows on dmarc reports tab - what am I missing? The dmarch email address does get cleaned up and dmarc folder has XML files in them... but the page is completely blank (screenshot below) 

https://mailadmin.xxxxx.net/?page=dmarcreports

![image](https://user-images.githubusercontent.com/35237867/123319359-eb9dde80-d4f5-11eb-9931-ce7dff6dfa08.png)

**Comment by umairmalik2410** [comment]
Screenshot for dmarcreports folder (redacted some info)

![image](https://user-images.githubusercontent.com/35237867/123319975-c198ec00-d4f6-11eb-8e95-993f94b50349.png)

**Comment by umairmalik2410** [comment]
I also don't see an errors in the developer tools (f12 on google chrome)

**Comment by coax** [comment]
@tunis78 can you take a look at this issue please?

**Comment by tunis78** [comment]
As your screenshot show you have over 12k reports in the directory.
I think your php timeout.
Test to move some reports and test only with a few.

**Comment by umairmalik2410** [comment]
Tested with 180~ reports and it worked!

Tested with 600~ and it worked as well - will try to increase PHP timeout

I guess it would be a "nice-to-have" if such a situation can be handled by the code and an error is displayed. 

@tunis78 & @coax - Thank you for your help and your hard work is appreciated.
