### ISSUE TITLE
Feature request? TLS-RPT parsing

### ISSUE THREAD

**Issue by kimboslice99** [coax/hmailserver-webadmin#44]
I can see its been a couple years since any update, so I'm not sure if this project died, nonetheless thought I'd mention

Would be cool to see a TLS report panel added? Would go along nicely with the dmarc report panel

I could probably do it myself but it wouldnt be nearly the same quality work thats been done here, heh

**Comment by coax** [comment]
Hey, this project is focused on redesign only. Not adding any scripts/pages outside the scope of PHPWebAdmin.

**Comment by kimboslice99** [comment]
Well I came back to this after learning quite a bit and wrote it myself :) just wanted to report back here for others

My fork can be found [here](https://github.com/kimboslice99/hmailserver-webadmin)
