### ISSUE TITLE
Google Dmar report in json format

### ISSUE THREAD

**Issue by gotspatel** [coax/hmailserver-webadmin#47]
Hello,

google, yahoo has started sending DMARC reports in json format rather then xml.

Can you please look into it and advise the changes

**Comment by bin-inge** [comment]
You can set dmarc format in your dmarc record. I use "v=DMARC1; p=reject; rua=mailto:dmarc@domain.ltd; ruf=mailto:dmarc@domain.ltd; **rf=afrf**; sp=reject; fo=0:1:d:s; pct=100; ri=86400; adkim=s; aspf=r". I have no problems reading dmarc reports with this dmarc record in webadmin gui.
