### ISSUE TITLE
missing #

### ISSUE THREAD

**Issue by RvdHout** [coax/hmailserver-webadmin#48]
my mistake 😳

https://github.com/coax/hmailserver-webadmin/blob/master/hMailAdmin/js/core.js#L410

```
	// distributionlists
	if ($('#DistributionListMode').length) {
		console.log($('#DistributionListMode').find(':selected').val())
		if ($('#DistributionListMode').find(':selected').val() != 2) {
			$('#RequireSenderAddress').hide();
		}
		$('select[name="Mode"]').on('change', function() {
			if ($(this).val() != '2') {
				$('#RequireSenderAddress').hide();
			} else {
				$('#RequireSenderAddress').show();
			}
		});
	}
```

**Comment by coax** [comment]
Thanks. I'm currently working on v1.7 (redesign) and will include the fix there. Let me know if you find anything else.

**Comment by RvdHout** [comment]
https://github.com/coax/hmailserver-webadmin/blob/master/hMailAdmin/include_treemenu.php#L91
```
	$TotalWhiteListAddresses = $obSettings->AntiSpam->WhiteListAddresses->Count();
	$TotalGreyListWhiteListAddresses = $obSettings->AntiSpam->GreyListingWhiteAddresses->Count();
```

https://github.com/coax/hmailserver-webadmin/blob/master/hMailAdmin/include_treemenu.php#L133

```
                <li class="has-children">
					<a href="?page=greylisting" class="more"><?php EchoTranslation("Greylisting") ?></a>
					<ul>
						<li><a href="?page=greylistingwhiteaddresses"><?php EchoTranslation("Greylisting White listing") ?><span class="count"><?php echo $TotalGreyListWhiteListAddresses ?></span></a></li>
					</ul>
				</li>
```

**Comment by RvdHout** [comment]
hm_mirror.php maybe needs a additional checkbox, if checkbox enabled validate email address and make required
if unchecked clear mirroremailaddress value & clear required tag

There is currently no way to clear mirroremailaddress value once it is set

**Comment by coax** [comment]
> hm_mirror.php maybe needs a additional checkbox, if checkbox enabled validate email address and make required if unchecked clear mirroremailaddress value & clear required tag
> 
> There is currently no way to clear mirroremailaddress value once it is set

Done.
