### ISSUE TITLE
User front-end

### ISSUE THREAD

**Issue by bajlek** [coax/hmailserver-webadmin#5]
Hi, admin page is working fine, but user page in not working $page is not showing. See attached picture. Old web UI is OK. Can you tell what am I doing wrong?

Windows Server 2012 R2 last hMail

![error_user_frontend_no_options](https://cloud.githubusercontent.com/assets/27892518/25304954/340e9636-2772-11e7-9b29-7769f8c59a88.png)

**Comment by coax** [comment]
Download the latest release v1.1, many things have been fixed since v0.9.3 beta
