### ISSUE TITLE
Account -Error v1.7

### ISSUE THREAD

**Issue by michalhana99** [coax/hmailserver-webadmin#50]
![image](https://github.com/user-attachments/assets/eae0313a-d46e-4263-8f48-72042417f7fa)

**Comment by coax** [comment]
Can you replace this (line 129) in _hm_account.php_:

```
$date = DateTime::createFromFormat('m/d/Y h:i:s A', $AccountLastLogonTime);
$date_time = $date->format('d.m.Y H:i:s');

PrintPropertyRow("Last logon time", $date_time);
```

with this:
```
// Convert string to Unix time
$unixTime = strtotime($AccountLastLogonTime);
// Pass the new date format as a string and the original date in Unix time
$AccountLastLogonTime = date("d.m.Y H:i:s", $unixTime);

PrintPropertyRow("Last logon time", $AccountLastLogonTime);
```

and let me know if it works for you?

**Comment by gotspatel** [comment]
Yes this change will solve it

I had done it and working (time format i have set for my convenience)

$EpochTime = strtotime($AccountLastLogonTime);
$AccountLastLogonTime = date("Y/m/d h:i:s A", $EpochTime);
PrintPropertyRow("Last logon time", $AccountLastLogonTime);

**Comment by coax** [comment]
Great, closing issue and pushing change to master.
