### ISSUE TITLE
Scripting

### ISSUE THREAD

**Issue by RvdHout** [coax/hmailserver-webadmin#51]
Do the 'reload scripts' and 'check syntax' button do anything? 

Sure doesn't look like it... not sure how long this issue existed pre 1.7
Uncaught ReferenceError: formCheck is not defined

**Comment by RvdHout** [comment]
correction: check syntax seems to work fine, reload scripts doesn't, should we just remove onsubmit="return formCheck(this);"?

**Comment by coax** [comment]
Just checked it, it doesn't output anything (all the work is done in background) so I removed the onsubmit="return formCheck(this);". Result message will be shown on page so there is some sort of response after clicking the button.

**Comment by coax** [comment]
Changed in v1.8 (pre-release): https://github.com/coax/hmailserver-webadmin/commit/3c5eb2b43d6cd18e72d5d08f7164c380b5d80ff9

**Comment by RvdHout** [comment]
A result message should not have been added (if you ask me) it simple has to post back, it didn't due to Uncaught ReferenceError: formCheck is not defined

**Comment by coax** [comment]
formCheck has been completely removed in v1.8 and the result is something that is passed by COM API and shown to user as a logical result that something happened.

**Comment by coax** [comment]
I don't think we need to spend any more time on this :) If you can, please check DMARC reports and TLS reports because I do changes and testing on live server which does not have these enabled.

**Comment by RvdHout** [comment]
Me neither, or at least no TLS reports... DMARC reports works fine against 1.7 (not tested 1.8 yet)
