### ISSUE TITLE
Operation failed on edit account

### ISSUE THREAD

**Issue by bin-inge** [coax/hmailserver-webadmin#53]
I have this problem when trying to edit an account.

Operation failed
Description: Call to a member function format() on bool

Line: 130

Script: hm_account.php

Thank you for your good work.

**Comment by bin-inge** [comment]
For now I just removed this lines in hm_account.php

	$date = DateTime::createFromFormat('m/d/Y h:i:s A', $AccountLastLogonTime);
	$date_time = $date->format('d.m.Y H:i:s');

	PrintPropertyRow("Last logon time", $date_time);

**Comment by coax** [comment]
Yes, this has been fixed already in v1.8. I will not yet publish the release (needs more testing) but you can still download the updated code directly from https://github.com/coax/hmailserver-webadmin > Code > Download ZIP.

**Comment by bin-inge** [comment]
Thanks, Tried v1.8. and works great. Thanks
