### ISSUE TITLE
Date Time of Account Last Logon Time Parse Issue After 1.8 Update

### ISSUE THREAD

**Issue by odixz** [coax/hmailserver-webadmin#54]
After updating to 1.8 the account last logon time in Account page default to unix epoch time as seen in this screenshot
 
![image](https://github.com/user-attachments/assets/9c583010-7a45-475c-afc8-fcbbb39897bb)

Is it because $AccountLastLogonTime return datetime string with dot as separator in it that strtotime() fail to parse it?

**Comment by coax** [comment]
The script converts your local date (no matter which format it is) into a Unix timestamp and then formats it to 'Y-m-d H:i:s' because it's universal datetime format for web admin. It should work, can you check the original datetime value from SQL database (hmailserver > hm_accounts > accountlastlogontime)?

**Comment by odixz** [comment]
Here are some of accountlastlogontime values in hm_accounts table 
![image](https://github.com/user-attachments/assets/f8077210-2185-4d0b-bcb2-c9a73673ec40)
and here is $AccountLastLogonTime original value before being converted into unix timestamp and my locale setting is set to Indonesia which in Windows Server 2016 use dot as the time separator.
![image](https://github.com/user-attachments/assets/40f3d7e1-2b19-4e84-b834-0fe01f672998)
Edit:
Ok, after some testing it's the slash not the dot that was making strtotime fail to parse, according to [this stackoverflow thread](https://stackoverflow.com/questions/2891937/strtotime-doesnt-work-with-dd-mm-yyyy-format)  however looking at [strtotime documentation](https://www.php.net/manual/en/function.strtotime.php) there are no mention regarding datetime format with slash as date separator. Oh there is a link in there to [date time format documentation](https://www.php.net/manual/en/datetime.formats.php) apparently, it seems that when using slash as date separator with the year part on the back strtotime only parse if it's in american date notation mm/dd/yy it doesn't accept dd/mm/yy format. So to use dd/mm/yy format before parsing it with strtotime we have to replace the slashes with either tabs, dashes or dots so it becomes dd mm yy or dd-mm-yy or dd.mm.yy Am I reading this correctly?

**Comment by coax** [comment]
Insert this to line 129 of _hm_account.php_:

```
	// Prepare string for Unix time
	$AccountLastLogonTime = str_replace('/', '-', $AccountLastLogonTime);
	// Convert string to Unix time
	$unixTime = strtotime($AccountLastLogonTime);
	// Pass the new date format as a string and the original date in Unix time
	$AccountLastLogonTime = date('Y-m-d H:i:s', $unixTime);
```

**Comment by odixz** [comment]
Yup that solves it, thank you.

**Comment by odixz** [comment]
I know this has been solved. I'd just like to share this script modified from the one provided by @coax, so that the patch works on servers using slash as the date separator in american date format or non-american date format. Adding function to check if date format used by the server uses slash as date separator and also the first part of the date pattern is day in month before replacing the separator from slash with dash.
```
	//function to get the date format used by this server 
	function getDateFormat($locale) {
		$formatter = new IntlDateFormatter($locale, IntlDateFormatter::SHORT, IntlDateFormatter::NONE);
		if ($formatter === null)
			throw new InvalidConfigException(intl_get_error_message());

		return $formatter->getPattern();
	}
	// Prepare string for Unix time if server locale date format uses slash as seperator and the first part is day in month
	if (preg_match('/^[dD].*\//', getDateFormat(Locale::getDefault()))) {
		$AccountLastLogonTime = str_replace('/', '-', $AccountLastLogonTime);
	}
	// Convert string to Unix time
	$unixTime = strtotime($AccountLastLogonTime);
	// Pass the new date format as a string and the original date in Unix time
	$AccountLastLogonTime = date('Y-m-d H:i:s', $unixTime);
```
edit: formatting and I almost forgot, this require intl module extension enabled in php.ini
